language: php
php:
  - '7.0'
  - '7.1'

#before_script:
#  - composer install

script:
  - docker run --rm -v $PWD:/app phpqa/security-checker security:check
  #- docker run --rm -v $PWD:/app phpqa/phpcs .
  - php phpcs.phar -n index.php
  # - phpunit
  - ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests/EmailTest

notifications:
  email:
    on_success: never
    on_failure: always

